workflows:
  react-native-android:
    name: React Native Android APK
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_play  # Optional if you're not uploading to Google Play
      vars:
        PACKAGE_NAME: "com.sinmichael.sample.reactnative"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: npm install
      - name: Fix Gradle Permissions
        script: chmod +x android/gradlew
      - name: Increment Version Code
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z "$LATEST_GOOGLE_PLAY_BUILD_NUMBER" ]; then
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          echo "Using version code: $UPDATED_BUILD_NUMBER"
      - name: Build Android APK
        script: | 
          cd android
          ./gradlew assembleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
