workflows:
  build_android:
    name: Build React Native Android APK
    environment:
      vars:
        NODE_VERSION: 18.18.0  # Adjust based on your React Native version
      working_directory: "."
    scripts:
      - name: Install Dependencies
        script: yarn install
      - name: Clean Android Build
        script: cd android && ./gradlew clean && cd ..
      - name: Set Up Gradle Properties
        script: |
      - name: Build Android APK
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
